
import React from 'react';

const Privacy: React.FC = () => {
  return (
    <div className="animate-in fade-in duration-1000 py-24 px-6 min-h-screen">
      <div className="max-w-4xl mx-auto">
        {/* HERO SECTION */}
        <div className="mb-24">
          <div className="inline-block px-3 py-1 bg-[#F9FAFB] text-[10px] font-bold uppercase tracking-widest text-[#6B7280] mb-8 rounded-full border border-gray-100">Legal Information</div>
          <h1 className="text-5xl md:text-8xl font-bold tracking-tighter mb-6 text-[#0B0B0B]">Privacy Policy.</h1>
          <p className="text-xl text-[#6B7280] leading-relaxed max-w-2xl">
            How we collect, use, and protect your information at Legal Success India.
          </p>
        </div>

        <div className="space-y-20 text-[#6B7280] leading-relaxed">
          
          {/* SECTION 1: Company Information */}
          <section className="animate-in slide-in-from-bottom-4 duration-700">
            <h2 className="text-2xl font-bold text-[#0B0B0B] mb-8 tracking-tight">1. Company Information</h2>
            <div className="p-8 bg-[#F9FAFB] rounded-[2rem] border border-gray-100 space-y-4 text-sm md:text-base">
              <p><span className="font-bold text-[#0B0B0B]">Company Name:</span> Legal Success India (Khalid Legal Works Private Limited)</p>
              <p><span className="font-bold text-[#0B0B0B]">CIN:</span> U70200WB2024PTC270336</p>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-4 border-t border-gray-200/50">
                <div>
                  <p className="font-bold text-[#0B0B0B]">Director</p>
                  <p>Azsed Anwar – DIN 10614233</p>
                </div>
                <div>
                  <p className="font-bold text-[#0B0B0B]">Director</p>
                  <p>Arshed Anwar – DIN 10614234</p>
                </div>
              </div>
              <p className="pt-4 border-t border-gray-200/50">
                <span className="font-bold text-[#0B0B0B]">Registered Office:</span><br />
                22/1 Mominpore Road, Kolkata, West Bengal – 700023
              </p>
              <p><span className="font-bold text-[#0B0B0B]">Email:</span> info@legalsuccessindia.com</p>
            </div>
          </section>

          {/* SECTION 2: General Information */}
          <section className="animate-in slide-in-from-bottom-4 duration-700">
            <h2 className="text-2xl font-bold text-[#0B0B0B] mb-6 tracking-tight">2. General Information</h2>
            <div className="space-y-4">
              <p>This Privacy Policy is an electronic record under the Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
              <p>The Website is operated by Legal Success India. Your use of the Website and services and tools are governed by this Privacy Policy along with our Terms & Conditions. By using the Website, you signify your agreement to be bound by these policies.</p>
            </div>
          </section>

          {/* SECTION 3: Definitions */}
          <section className="animate-in slide-in-from-bottom-4 duration-700">
            <h2 className="text-2xl font-bold text-[#0B0B0B] mb-6 tracking-tight">3. Definitions</h2>
            <ul className="space-y-4 list-disc pl-5">
              <li><span className="font-bold text-[#0B0B0B]">User / You:</span> Refers to any person who visits or accesses the website.</li>
              <li><span className="font-bold text-[#0B0B0B]">We / Us / Our:</span> Refers to Legal Success India and its representatives.</li>
              <li><span className="font-bold text-[#0B0B0B]">Website:</span> Refers to www.legalsuccessindia.com.</li>
            </ul>
          </section>

          {/* SECTION 4: Information We Collect */}
          <section className="animate-in slide-in-from-bottom-4 duration-700">
            <h2 className="text-2xl font-bold text-[#0B0B0B] mb-6 tracking-tight">4. Information We Collect</h2>
            <p className="mb-6">We collect personal and business information that is necessary to provide our consultancy services effectively:</p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
              <div className="p-6 bg-gray-50 rounded-2xl">
                <h4 className="font-bold text-[#0B0B0B] mb-2">Personal & Business Details</h4>
                <p className="text-sm">Name, email, phone number, address, and relevant business compliance details.</p>
              </div>
              <div className="p-6 bg-gray-50 rounded-2xl">
                <h4 className="font-bold text-[#0B0B0B] mb-2">Documents & Messages</h4>
                <p className="text-sm">Uploaded files for registration purposes and records of our communications.</p>
              </div>
            </div>
            <p><span className="font-bold text-[#0B0B0B]">Purpose:</span> We use this data for service delivery, compliance support, and improving user experience.</p>
          </section>

          {/* SECTION 5: Automatic Data Collection */}
          <section className="animate-in slide-in-from-bottom-4 duration-700">
            <h2 className="text-2xl font-bold text-[#0B0B0B] mb-6 tracking-tight">5. Automatic Data Collection</h2>
            <p>We may automatically track certain information about you based upon your behavior on our Website. We use this information to do internal research on our users' demographics, interests, and behavior to better understand, protect and serve our users. This information may include the URL that you just came from, which URL you next go to, your computer browser information, and your IP address.</p>
          </section>

          {/* SECTION 6: Cookies Policy */}
          <section className="animate-in slide-in-from-bottom-4 duration-700">
            <h2 className="text-2xl font-bold text-[#0B0B0B] mb-6 tracking-tight">6. Cookies Policy</h2>
            <p>We use "cookies" on certain pages of the Website to help analyze our web page flow, measure promotional effectiveness, and promote trust and safety. Cookies are small files placed on your hard drive that assist us in providing our services. Most cookies are "session cookies," meaning that they are automatically deleted from your hard drive at the end of a session. You are always free to decline our cookies if your browser permits.</p>
          </section>

          {/* SECTION 7: Use & Sharing of Information */}
          <section className="animate-in slide-in-from-bottom-4 duration-700">
            <h2 className="text-2xl font-bold text-[#0B0B0B] mb-6 tracking-tight">7. Use & Sharing of Information</h2>
            <p>Your personal data is used internally and shared only with trusted service partners (like CAs or legal experts) necessary to fulfill your request. We may disclose personal information if required to do so by law or in the good faith belief that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal process. <span className="font-bold text-[#0B0B0B]">We never sell your personal data to third parties.</span></p>
          </section>

          {/* SECTION 8: Data Security */}
          <section className="animate-in slide-in-from-bottom-4 duration-700">
            <h2 className="text-2xl font-bold text-[#0B0B0B] mb-6 tracking-tight">8. Data Security</h2>
            <p>We implement reasonable administrative and technical safeguards designed to protect your information from unauthorized access. However, no data transmission over the Internet can be guaranteed to be 100% secure. By using the Website, you acknowledge the inherent risks of online data transmission.</p>
          </section>

          {/* SECTION 9: User Rights */}
          <section className="animate-in slide-in-from-bottom-4 duration-700">
            <h2 className="text-2xl font-bold text-[#0B0B0B] mb-6 tracking-tight">9. User Rights</h2>
            <p className="mb-4">You have the following rights regarding your personal data:</p>
            <ul className="space-y-2 list-disc pl-5">
              <li>Right to access your personal data held by us.</li>
              <li>Right to correct inaccuracies or complete incomplete information.</li>
              <li>Right to withdraw your consent for data processing at any time.</li>
              <li>Right to opt-out of marketing communications.</li>
            </ul>
            <p className="mt-4">To exercise these rights, please contact us at <span className="font-bold text-[#0B0B0B]">info@legalsuccessindia.com</span>.</p>
          </section>

          {/* SECTION 10: Third-Party Links */}
          <section className="animate-in slide-in-from-bottom-4 duration-700">
            <h2 className="text-2xl font-bold text-[#0B0B0B] mb-6 tracking-tight">10. Third-Party Links</h2>
            <p>Our Website may contain links to other websites that may collect personally identifiable information about you. Legal Success India is not responsible for the privacy practices or the content of those linked websites.</p>
          </section>

          {/* SECTION 11: Children’s Privacy */}
          <section className="animate-in slide-in-from-bottom-4 duration-700">
            <h2 className="text-2xl font-bold text-[#0B0B0B] mb-6 tracking-tight">11. Children’s Privacy</h2>
            <p>We do not intentionally collect personal information from children under the age of 13. If we discover that a child under 13 has provided us with personal information, we will delete such information from our servers immediately.</p>
          </section>

          {/* SECTION 12: Governing Law & Jurisdiction */}
          <section className="animate-in slide-in-from-bottom-4 duration-700">
            <h2 className="text-2xl font-bold text-[#0B0B0B] mb-6 tracking-tight">12. Governing Law & Jurisdiction</h2>
            <p>This Privacy Policy shall be governed by and interpreted and construed in accordance with the laws of India. The place of jurisdiction shall be exclusively in Kolkata, West Bengal.</p>
          </section>

          {/* SECTION 13: Policy Updates */}
          <section className="animate-in slide-in-from-bottom-4 duration-700">
            <h2 className="text-2xl font-bold text-[#0B0B0B] mb-6 tracking-tight">13. Policy Updates</h2>
            <p>Our Privacy Policy is subject to change at any time without notice. To make sure you are aware of any changes, please review this policy periodically. Your continued use of the Website implies acceptance of the updated policy.</p>
          </section>

          {/* SECTION 14: Contact Information */}
          <section className="animate-in slide-in-from-bottom-4 duration-700 bg-black text-white p-12 rounded-[3rem]">
            <h2 className="text-2xl font-bold mb-6 tracking-tight">14. Contact Information</h2>
            <p className="text-gray-400 mb-8">For any grievances or questions regarding this policy, please reach out to us:</p>
            <div className="space-y-4 font-medium">
              <p>Legal Success India</p>
              <p>22/1 Mominpore Road, Kolkata – 700023</p>
              <p>Email: <span className="text-white">info@legalsuccessindia.com</span></p>
            </div>
          </section>

        </div>
      </div>
    </div>
  );
};

export default Privacy;
